#@TYPE: Machine
#@NAME: pic64hpsc
#@DESCRIPTION: Generic support for PIC64-HPSC/HX

require include/pic64hpsc.inc

SERIAL_CONSOLES ?= "115200;ttyS0"

# Build as an initrd
IMAGE_FSTYPES += "cpio.gz"

# Build the bootloader and OpenSBI as part of the image.
EXTRA_IMAGEDEPENDS += "virtual/bootloader opensbi"

# VSC857x firmware
MACHINE_EXTRA_RRECOMMENDS += "linux-firmware-microchip"

